### ISSUE TITLE
When clicking month of Datepicker then getting error: Attempt to invoke interface method 'int com.facebook.react.bridge.readablearray.size()' on a null object reference.

### ISSUE THREAD

**Issue by zhongqitech** [akveo/react-native-ui-kitten#1694]
When clicking month of Datepicker then getting error:
"Attempt to invoke interface method 'int com.facebook.react.bridge.readablearray.size()' on a null object reference"

![20221225232155](https://user-images.githubusercontent.com/7759842/209473658-1cfa73ec-85bf-4012-bbf2-b4cb5eea10a4.jpg)

![20221225231527](https://user-images.githubusercontent.com/7759842/209473450-fdf4f734-0223-40ea-8938-25056309bf3b.jpg)

**Comment by zhongqitech** [comment]
The question on StackOverflow: [https://stackoverflow.com/questions/74844166/datepicker-clicking-month-error-attempt-to-invoke-interface-method-int-com-fac](url)

**Comment by Stekmo** [comment]
Experiencing the same. Running expo@47.0.8 and react-native@0.70.5.
Issue seems to occur only on Android.

**Comment by zhongqitech** [comment]
Thank you @Stekmo 
It's a big bug on android has not been fixed. Hope official team or someone figure it out as soon as possible.

**Comment by HernandezDev** [comment]
Same issue here. Using expo@~47.0.12 and react-native@0.70.5.

Have you found a workaround for this?

**Comment by PatrykMoskal** [comment]
Had to change to different library because of that bug on android.

**Comment by zhongqitech** [comment]
Hi guys,
Nothing to do but just updated RN 0.70.3 to 0.70.7 & reinstall @ui-kitten/components and then the bug has gone.
It seems the bug fixed by maintainers. Thanks!

**Comment by obayit** [comment]
In my case the bug still exists, react-native version `0.71.3` and @ui-kitten/components version `5.1.2`

**Comment by sergey-kozel** [comment]
@obayit could you please provide minimal project setup/dependencies (or test project) for reproducing the issue?

**Comment by sergey-kozel** [comment]
fixed in 5.3.1
