### ISSUE TITLE
Image rkCardImg doesn't work

### ISSUE THREAD

**Issue by ventskus-roman** [akveo/react-native-ui-kitten#20]
I've tried code from examples:
```
<RkCard>
        <View rkCardHeader>
          <Text>Header</Text>
        </View>
        <Image rkCardImg source={require('../img/sea.jpg')}/>
        <View rkCardContent>
          <Text> quick brown fox jumps over the lazy dog</Text>
        </View>
        <View rkCardFooter>
          <Text>Footer</Text>
        </View>
</RkCard>
```

But image doesn't shown on the screen. See screenshot

<img width="343" alt="2017-07-03 14 52 17" src="https://user-images.githubusercontent.com/959926/27791809-8a4dbe08-5fff-11e7-98d9-075c8c6e11a6.png">

But if I set `style={{width: 200, height: 200}}` and remove **rkCardImg** attribute for Image element - it appears on the screen. Probably something wrong with processing of **rkCardImg** attribute

**Comment by SashaSkywalker** [comment]
Hello

I tried reproduce that behavior but on android and ios your example works correctly.
Maybe in some place of your app style of ```rkCardImage``` is changed?

I have following styles for ```<Image>```:
![image](https://user-images.githubusercontent.com/6690616/28311691-20351906-6bb9-11e7-9030-d2f535b5beb5.png)

**Comment by SashaSkywalker** [comment]
After some research I understand that the problem is useless style ```flex: 1``` for image, we will fix it in next release

**Comment by jbaek7023** [comment]
Did you fix the bug?

**Comment by GregorHorvatH** [comment]
workaround:

        RkTheme.setType('RkCard', 'story', {
            img: {
                **flex: 0,**
                height: 100,
                opacity: 0.7
            },

**Comment by sergey-kozel** [comment]
Hi @ventskus-roman, @jbaek7023 , @GregorHorvatH,

This issue is fixed in d22d195951ffe4b102c1a63b5ef356520da937f. The fix will be included into next release.

**Comment by 1k2k** [comment]
@sergey-kozel still having this issue in v3.0.0 from android only
