### ISSUE TITLE
Bottom navigation with icons: invalid props tintColor

### ISSUE THREAD

**Issue by justasam** [akveo/react-native-ui-kitten#548]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report?
* [ ] feature request

### Issue description

**Current behavior:**
When I add any icons to bottom tab navigation (e.g. @expo/vector-icons) it shows me 
Warning: Failed prop type: Invalid props.style key `tintColor` supplied to `Text`.

**Expected behavior:**
no warnings.

**Steps to reproduce:**
I've basically copy-pasted "With React Navigation API and usage example" from Bottom Navigation documentation and added few icons from @expo/vector-icons to the tabs. 

**Related code:**

```
import { MaterialIcons } from '@expo/vector-icons';

const WalletIcon = ({ tintColor }) => 
  <MaterialIcons color={tintColor} name="compare-arrows" size={24} />

<BottomNavigationTab title='Accounts' icon={WalletIcon} />
```

### Other information:

**OS, device, package version**
```
WIN10, Android Emulator API 29
```

**Comment by artyorsh** [comment]
Fortunately, we've already faced this issue and currently working on it.
The reason is that `vector-icons` render a Text, which we didn't expect to be returned from `icon` prop. This will be fixed in the next version

Thanks for reporting this

**Comment by artyorsh** [comment]
There are two options for you now:
- Configure YellowBox to ignore this type of warning
- Use any other icons library that renders SVG (e.g [Eva Icons](https://github.com/artyorsh/react-native-eva-icons)), or simply use an `Image` component

Again, the fix will be available in the next release :)

**Comment by tgdn** [comment]
What's the state of this?

**Comment by artyorsh** [comment]
@tgdn I guess this is fixed in latest versions. Furthermore, we have released `@ui-kitten/eva-icons` package which works pretty well with all components distributed with UI Kitten

**Comment by deveshrawat** [comment]
it still not fixed i am facing the same issue .

**Comment by 0plus1** [comment]
This still happens when using BottomNavigationTab

**Comment by artyorsh** [comment]
Hi everyone 👋 

This still happens just because by default, we expect icon it to be an `Image`. Since vector icons relies on `Text` component, this issue occurs. 

You're able to configure 3rd party icon libraries like [by following this guide](https://akveo.github.io/react-native-ui-kitten/docs/guides/3rd-party-icons#3rd-party-icon-libraries). We explain how to use `react-native-vector-icons` icons package, but same technique can be applied to `@expo/vector-icons`

**Comment by seyaobey** [comment]
@artyorsh the link to the guide is broken
I landed here from this [stackoverflow question](https://stackoverflow.com/questions/57013538/react-native-icons-warning-failed-prop-type-invalid-props-style-key-tintcol)

**Comment by artyorsh** [comment]
@seyaobey sorry, we've updated docs recently. 3rd party icons guide is now [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/icon-packages#3rd-party-icon-packages)

**Comment by lyonsbp** [comment]
I still have this issue, even when using the `@ui-kitten/eva-icons` package. I get the error: "TypeError: Undefined is not an object (evaluating 'iconElement.props').

I am following the "Bottom navigation with icons" example here: https://akveo.github.io/react-native-ui-kitten/docs/components/bottom-navigation/overview#bottomnavigationtab

I have the icons setup in the repo already, and they work in other components like buttons etc. I also cannot find any live examples online of bottom nav working with icons. Can you confirm it works?

**Comment by artyorsh** [comment]
@lyonsbp yes I can. Can you please provide related code and library versions?

**Comment by lyonsbp** [comment]
Sure. Its a private repo for an internal hackathon but I can share the relevant 2 files.

App.js:
```
import React from 'react';
import {StyleSheet, View, StatusBar} from 'react-native';
import 'react-native-gesture-handler';
import {Colors} from 'react-native/Libraries/NewAppScreen';

import {
  ApplicationProvider,
  Button,
  IconRegistry,
  Icon,
} from '@ui-kitten/components';
import {EvaIconsPack} from '@ui-kitten/eva-icons';
import {mapping, light as theme} from '@eva-design/eva';
import {AppNav} from './src/components/AppNav/AppNav';

export const FacebookIcon = style => <Icon name="facebook" {...style} />;

export const LoginButton = () => <Button icon={FacebookIcon}>Icon Test</Button>;

const App = () => {
  return (
    <React.Fragment>
      <IconRegistry icons={EvaIconsPack} />
      <ApplicationProvider mapping={mapping} theme={theme}>
        <StatusBar barStyle="dark-content" />
        <View>
          <LoginButton />
        </View>
        <AppNav />
      </ApplicationProvider>
    </React.Fragment>
  );
};
```

AppNav.js
```
const BookmarkIcon = style => {
  <Icon name="bookmark-outline" {...style} />;
};

const HomeIcon = style => {
  <Icon name="home-outline" {...style} />;
};

const SearchIcon = style => {
  <Icon name="search-outline" {...style} />;
};

const TabBarComponent = ({navigation}) => {
  const onSelect = index => {
    const selectedTabRoute = navigation.state.routes[index];
    navigation.navigate(selectedTabRoute.routeName);
  };

  return (
    <SafeAreaView>
      <BottomNavigation
        selectedIndex={navigation.state.index}
        onSelect={onSelect}>
        <BottomNavigationTab title="SAVED" />
        <BottomNavigationTab title="COOKTENT" />
        <BottomNavigationTab title="SEARCH" />
      </BottomNavigation>
    </SafeAreaView>
  );
};
```

If you need anything else let me know. The nav works great as is without the icons. However, if I replace the `title="Saved"` prop with `icon={BookmarkIcon}` I get the error I stated earlier. 
The icon in the app.js file works great so I know the icons are working right.

**Comment by artyorsh** [comment]
@lyonsbp You can find live examples of BottomNavigation with icons by the link you shared. Could you clarify you have `tintColor` or`Undefined is not an object` issue? Also, can you confirm it will lead to the same error when using within navigator? (I mean in case it's rendered somewhere deeper in tree hierarchy)

**Comment by globophobe** [comment]
Set up bottom navigation with tabs, as described in https://akveo.github.io/react-native-ui-kitten/docs/components/bottom-navigation/overview#bottomnavigation

If I try to adding an icon, the following error is thrown:

`Exception thrown while executing UI block: -[__NSCFNumber firstObject]: unrecognized selector sent to instance...`

**Comment by NazarDevsMedia** [comment]
in my case I am facing this error `Warning: Failed prop type: Invalid props.style key `tintColor` supplied to `Text`` while using @expo/vector-icons as Input's accessory, quick fix for me is to wrap icon with fragment and warning will disappear.

**Comment by hayelom123** [comment]
[NazarDevsMedia](https://github.com/NazarDevsMedia)
you are right wrapping it reslolved the problem

**Comment by ilanRosenbaum** [comment]
Getting this error after upgrading from 0.70 to 0.73
